### ISSUE TITLE
Destructive error when building with Vite

### ISSUE THREAD

**Issue by FeiFanLiang** [ghostdevv/rollup-obfuscator#148]
<img width="771" alt="image" src="https://github.com/ghostdevv/rollup-obfuscator/assets/30872365/235f9827-c917-4283-98b1-ccb6c7093290">
<img width="771" alt="image" src="https://github.com/ghostdevv/rollup-obfuscator/assets/30872365/f5e436d2-79d6-47ad-9bde-f20fb2a2c567">

When building, the error `this?.debug is not a function `will be prompted.
I solved the problem by manually deleting these two lines in the code, but the built product did not run properly.

![image](https://github.com/ghostdevv/rollup-obfuscator/assets/30872365/c4b7387d-40a5-439c-83c2-59f67b6bfa56)

I used Typescript's alias,This resulted in the project not being able to find the page file for the response

I uploaded a minimally reproducible code to the warehouse, and I only need to run pnpm build pnpm preview to reproduce it.
https://github.com/FeiFanLiang/rollup-obfuscator-debugger

**Comment by GabrielMahan** [comment]
experiencing this as well.

**Comment by GabrielMahan** [comment]
Not totally sure how the debugging stuff is supposed to work, but I made a quick PR to address: https://github.com/ghostdevv/rollup-obfuscator/pull/149.

**Comment by ghostdevv** [comment]
@GabrielMahan @FeiFanLiang could you confirm that this is now fixed in `v4.1.1`?

**Comment by thierrymichel** [comment]
No, I still have a similar issue.
Removing the 2 `this.debug` lines does not change anything.

I do not have time (right now) to create a minimal reproducible example but what I observed :

- Happens with `stringArray: true`
- Generates errors on build like:
    - `src/modules/ui/App.vue (1:964): Error when using sourcemap for reporting an error: Can't resolve original location of error.`
    - not always the same files (kind of randomness)!
 - Crash the application with resolution error:
   - `TypeError: Failed to resolve module specifier '@/modules/ui/views/Idle.vue'` (which is imported in the App.vue…)
   - not always in the same way
   - probably related to the `random` behavior (see upper)
 
  I will try to make it reproducible somewhere later.

**Comment by thierrymichel** [comment]
FYI, similar behaviour with `rollup-plugin-obfuscator`

**Comment by z0ffy** [comment]
Try it with https://www.npmjs.com/package/vite-plugin-bundle-obfuscator
